# Generated by Django 3.2.18 on 2023-05-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0011_auto_20191022_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Created By'),
        ),
    ]
